import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthContextProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border bg-blue-300 text-white py-4 px-6 shadow-md flex flex-col md:flex-row items-start md:items-center">
          <h1 className="text-2xl font-bold mb-4 md:mb-0 md:mr-32 whitespace-nowrap">
            Let`s T-weet
          </h1>
          <nav className="flex flex-wrap gap-4 md:gap-6 md:flex-grow md:justify-between text-xl">
            <Link
              href="/"
              className="hover:text-blue-400 transition duration:200"
            >
              Home
            </Link>
            <Link
              href="/explore"
              className="hover:text-blue-400 transition duration:200"
            >
              Explore Tweets
            </Link>
            <Link
              href="/post"
              className="hover:text-blue-400 transition duration:200"
            >
              Post a Tweet
            </Link>
            <Link
              href="/trending"
              className="hover:text-blue-400 transition duration:200"
            >
              Trending
            </Link>
            <Link
              href="/profile"
              className="hover:text-blue-400 transition duration:200"
            >
              My Profile
            </Link>
            <Link
              href="/login"
              className="hover:text-blue-400 transition duration:200"
            >
              LogIn
            </Link>
          </nav>
        </header>

        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
