import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";
//import Logo from "components/Logo";
import Navbar from "components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContextProvider>
          <header className="border bg-blue-300 text-white py-4 px-6 shadow-md flex flex-col md:flex-row items-start md:items-center">
            {/*<Logo />*/}

            <h1 className="text-2xl font-bold mb-4 md:mb-0 md:mr-32 whitespace-nowrap">
              Let`s T-weet
            </h1>

            <Navbar />
          </header>

          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
