import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";
import Logo from "components/Logo";
import Navbar from "components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContextProvider>
          <header className="bg-blue-300 text-white py-6 px-4 shadow-md">
            <div className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center md:justify-between gap-4">
              <div className="flex items-center gap-4">
                <Logo />
                <h1 className="text-2xl font-bold whitespace-nowrap">
                  Let`s T-weet
                </h1>
              </div>

              <Navbar />
            </div>
          </header>

          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
